### ISSUE TITLE
Support for Ability to Index data for Samples and Check Responses

### ISSUE THREAD

**Issue by gingerwizard** [elastic/docs#133]
As part of consolidating [example watches](https://github.com/elastic/examples/tree/master/Alerting) into the documentation, we need to clarify the doc build process for supporting the following. The intention was to include the watches and utilise the doc build processes to test them.  Currently the Watches are distributed with a sample test harness that tests against the current version of ES only.  

If these are not supported, the proposal is to build enhance pending discussion.

1. The ability to declare a REST example and this be tested against a pre-determined dataset.  Does the build process support declaring the example, dataset and expected response?
2. Can we declare the dataset to be dynamic? Specifically, the current watch harness relies on offsetting the data against the current time - as most watches execute against now-Nmins.

Other thoughts:

- The actual call to execute the sample code maybe different than the sample e.g. insert watch, execute, matcher on response.
- Lower priority - Would we be able to execute a different build process or testing cycle depending on the version of ES/Xpack the page refers to.  What is the current support for this?

Thoughts please. @skearns64 @clintongormley @asawariS @debadair

**Comment by gingerwizard** [comment]
Should add opening this for discussion.  Others may feel this isn't the appropriate place for this type of integration testing.

**Comment by nik9000** [comment]
The Elasticsearch doc testing stuff is a gradle plugin. I'm not 100% clear on how you'd set it up but I can have a look at some point. The trouble is that it is part of Elasticsearch's build and not published as a separate thing. The idea is that you build the docs and Elasticsearch at the same time to make sure that the docs work with some particular version of Elasticsearch.

One way to get this "for free" would be to move the documentation into the docs in the x-pack repository.

> The ability to declare a REST example and this be tested against a pre-determined dataset. Does the build process support declaring the example, dataset and expected response?

Example data sets can be defined in build.gradle. [This](https://github.com/elastic/elasticsearch/blob/master/docs/build.gradle#L256-L322) links to two such setups for Elasticsearch's docs. You use them by adding a comment under the first snippet that needs them like [this](https://github.com/elastic/elasticsearch/blame/master/docs/reference/aggregations/pipeline/sum-bucket-aggregation.asciidoc#L62).

You can declare the expected response with another comment like [this](https://github.com/elastic/elasticsearch/blame/master/docs/reference/aggregations/pipeline/sum-bucket-aggregation.asciidoc#L111). You can use regex to replace sections of the response (or request) if you want. If you put `$body.some.path` then you can copy a portion of the response. This is useful for dynamic stuff like `took` in the link above.

Keep in mind you can also hide the responses in a block comment (`////`). The snippet extraction process will still extract it and use it for testing but it won't be rendered.


> Can we declare the dataset to be dynamic? Specifically, the current watch harness relies on offsetting the data against the current time - as most watches execute against now-Nmins.

Sure. Datasets declared in `build.gradle` are declared using groovy and you can write whatever you want. Those strings are mostly built at the start of the build so you shouldn't make the times too tight. "Five minutes ago" isn't ok without some work but "within 24 hours" is fine.

> The actual call to execute the sample code maybe different than the sample e.g. insert watch, execute, matcher on response.

Fine. You can wrap the actual call in block comments and mark the fake call with `// TEST[skip]`. I warn you doing that lowers the fidelity of the test a lot.

> Lower priority - Would we be able to execute a different build process or testing cycle depending on the version of ES/Xpack the page refers to. What is the current support for this?

This is the kind of thing you'd have to build when you set up testing. If you moved the example watches documentation into the x-pack documentation it'd always be built against the version you've committed it next to.

Note that none of this works for versions before 5.0. We have no doc testing for those versions because we never built the tools.

**Comment by dedemorton** [comment]
We can now pull samples from test cases. If there are additional requests, please open a new issue.
