### ISSUE TITLE
edit documentation button leads to an invalid CLA

### ISSUE THREAD

**Issue by cjcjameson** [elastic/docs#1783]
**Description of the problem including expected versus actual behavior**:

I found a small issue with the docs, and wanted to submit a fix ( elastic/elasticsearch#53945 ) . I saw the issue on a webpage showing the 7.6 docs, and there was an "edit" button.

I was already signed into Github, and so this brought me to a dedicated pull-request preparation page.

This is a really nice flow, except that the commit gets authored by `@users.noreply.github.com`. So when I sign the CLA with my actual `@gmail.com` account, it doesn't realized that I've signed the CLA.

**Steps to reproduce**:

Please include a *minimal* but *complete* recreation of the problem, including
(e.g.) index creation, mappings, settings, query etc.  The easier you make for
us to reproduce it, the more likely that somebody will take the time to look at it.

 1. Log into github
 2. Navigate to https://www.elastic.co/guide/en/elasticsearch/reference/current/mapping-routing-field.html and click "edit"
<img width="321" alt="image" src="https://user-images.githubusercontent.com/6885889/77336935-75ed0680-6ce5-11ea-9957-59f6a9e5b753.png">

 3. Propose a change
 4. observe CLA bot response

**Comment by jrodewig** [comment]
Transferred this to the elastic/docs repo. That's where the "Edit" link functionality is maintained.

**Comment by gtback** [comment]
Hi @cjcjameson! Thanks for taking the time to contribute to the Elasticsearch docs.

Based on my limited testing, I'm guessing that you have your email address marked as "private" [in GitHub's settings](https://help.github.com/en/github/setting-up-and-managing-your-github-user-account/setting-your-commit-email-address). (_Which I totally understand. I do too_.) And when you have that, GitHub doesn't give you a choice to use the email address you've used to sign the CLA. As a workaround, you can temporarily turn off that setting, make the commit, then turn it back on. I know that's not ideal, of course.

This should be something we can incorporate into our CLA checker directly. Since we have the username, we can check if the email address matches `ID+username@users.noreply.github.com` and allow the commit in that case. I'm checking on the implementation of that and will respond here once I learn more.

**Comment by gtback** [comment]
Our CLA checker should have been able to detect this, but since the commit was force-pushed after signing the CLA, we can't investigate any further right now. I'm closing this for now, but if anyone runs into this issue again, please reopen and I'll investigate.

**Comment by cjcjameson** [comment]
Thanks folks!
