### ISSUE TITLE
Explore moving some `conf.yaml` configuration over to their respective repos

### ISSUE THREAD

**Issue by jrodewig** [elastic/docs#1828]
### Problem
https://github.com/elastic/elasticsearch/pull/56067 relocates some integration tests within the ES repo. Some of these tests are also used in our docs.

The docs CI test for this PR failed because:
1)  The docs build was unaware of the new directory used to host the integration tests.
2) The docs build was expecting a file in the old directory for the tests. This directory had been removed.

The cause and source of the failure wasn't obvious, largely because configuration (`conf.yaml`) for ES-related docbooks are housed in the separate elastic/docs repo.

This made it practically impossible to implement the changes without temporarily breaking the docs build or merging a PR with a failing CI test.

### Proposal
We should explore the possibility of moving some or all of the `conf.yaml` configuration to their respective books. This would allow us to make atomic changes within one repo and make upkeep easier for repo maintainers.

**Comment by gtback** [comment]
> The docs CI test for this PR failed because the docs build was unaware of the new directory used to host the integration tests.

Was it because of the new directory existing, or because it was expecting the old (now missing) directory to be there? I can't see the builds anymore to look at the logs. I think there's a lot we can do, including better error messages.

On the broader issue, I'm OK with the idea of moving branch-specific information from `conf.yaml` into the source repo, so it can be updated along with the corresponding changes. It might only be worth it for the books which come from the elasticsearch repo, at least for now.

**Comment by jrodewig** [comment]
> Was it because of the new directory existing, or because it was expecting the old (now missing) directory to be there?

Good question. We saw both.

We need to both exclude the old directory and add the new directory for impacted branches.
Failure to do both results in an error. I'll update the original description to clarify.

**Comment by jrodewig** [comment]
This is no longer a priority now that development of a new docs system is underway. Closing this issue.
