### ISSUE TITLE
Snippets in docs don't use fixed width font on mobile

### ISSUE THREAD

**Issue by sylvie777** [elastic/docs#2057]
(Transferred from https://github.com/elastic/website-www.elastic.co/issues/3280)

Provide the following information to help us identify and troubleshoot the issue.
- Page URL: https://www.elastic.co/guide/en/elasticsearch/reference/6.x/sql-getting-started.html
- Device type: Pixel 3
- Specifics (e.g., OS, Hardware, Browser, etc.): Chrome

If you have a screenshot, add it below.
![screenshot_20181127-112815](https://user-images.githubusercontent.com/215970/49096334-5ef4ec00-f238-11e8-97ba-6502fab9f7b1.png)

The trouble with using a different font on mobile is that we rarely look at the pages on mobile so if there is a problem we're not likely to notice.

**Comment by gtback** [comment]
I can't reproduce this on Chrome on my Pixel 2. (though it redirects 6.x to 6.7, which should probably be 6.8, neither version of the page had this problem). My guess is that some styles from the main site were leaking into the docs, but that has since been fixed. If anyone still has this problem, please re-open.
