### ISSUE TITLE
Conditions of use <-> GPL conflict?

### ISSUE THREAD

**Issue by hogething** [elastic/docs#211]
How is Conditions of use justified if the repo clearly contains some GPL codeset?

I'm asking this because, to be honest, I want to use this build system for my personal business (don't ask me what kind of) due to asciidoctor's incompleteness & standard asciidoc's complications. It's not strictly required so I can workaround, but it would be a nice shortcut if I can use it.

**Comment by clintongormley** [comment]
Hi @hogething 

Just because the build script is calling GPL code doesn't make the script itself GPL, so I don't see any conflict there. Our main concern is that we don't want anybody else hosting the elastic docs.

This script is very much focussed on our internal work flow.  You should have a look at https://github.com/schacon/git-scribe which is a more generic tool

**Comment by hogething** [comment]
Very polite response for my silly question. Thank you.

**Comment by clintongormley** [comment]
:)
