### ISSUE TITLE
Spanish documentation.

### ISSUE THREAD

**Issue by cvazquezlos** [elastic/docs#250]
Hi all.

I am an enthusiast of Elastic and I think will be a great idea to provide the recent documentation (from 5.6 for example) in spanish, because there is a big community of spanish developers who use Elastic products everyday, like me, for example. Spanish is the second most spoken language.

Me and many others are avaible to work on it.

**Comment by debadair** [comment]
Thank you for your interest in contributing to the documentation for the Elastic stack. We are just starting to provide documentation in other languages and determining how best to manage the translation process and deliver and maintain translated content. 

While we ultimately want to enable community members to contribute to these efforts like we do for other aspects of our OSS projects, community-sourced translations of ever-changing documentation pose some unique challenges. They not only require an enormous amount of work to contribute and keep up to date (so unpaid community contributors are likely to get burnt out), they require significant, specialized resources for us to review and validate before they can be accepted. 

To date, the only real success we've had with community translated content has been with a very dedicated group of community volunteers in China who took on the mighty task of translating The Definitive Guide to Elasticsearch. Key factors in making it work were that it was a combined effort rather than a solo one, the rate of change in the English content they were translating was very low, and our local developer advocate was able to dedicate a significant amount of time to act as an internal champion and reviewer for the project.

Which is a long-winded way of saying that we agree that it would be great to have our docs available in Spanish, but we don't yet have a good framework for accepting community translations.

**Comment by cvazquezlos** [comment]
Thank you for your response.

I understand the situation. Anyways, I would be very happy to collaborate with you in the Spanish translation of ES documentation when you design that community translations policy.
