### ISSUE TITLE
Footnotes start with number 2

### ISSUE THREAD

**Issue by craigtaverner** [elastic/docs#2741]
When reviewing the new ESQL pow() function docs, I see that the footnotes start with index 2 (other than the expected 1).

This is what the page at https://www.elastic.co/guide/en/elasticsearch/reference/master/esql-pow.html says:

<img width="845" alt="Screenshot 2023-08-17 at 16 33 37" src="https://github.com/elastic/docs/assets/114451/542732bf-2702-43a2-9762-330d78cc84b8">

----

But when I view the relevant source document in Intellij, it renders the footnotes starting with the correct index:

<img width="991" alt="Screenshot 2023-08-17 at 16 33 24" src="https://github.com/elastic/docs/assets/114451/156a4049-f72e-419c-bfc3-1c661eb6b776">

**Comment by abdonpijpelink** [comment]
Footnotes are numbered consecutively throughout a book. For the Elasticsearch book, footnote number one is [here](https://www.elastic.co/guide/en/elasticsearch/reference/master/eql-function-ref.html#_footnotedef_1), which is why your footnotes start with number 2. I'm not sure this is something we can change, as it's been designed this way.

**Comment by craigtaverner** [comment]
Understood. It is visually a bit awkward because the pages with the footnotes are so separated. But if you are aware of this and happy with it, so am I. I think this is definitely in the docs domain, so your call is the final call.
