### ISSUE TITLE
Statement in doc is wrong: Timestamp when this message was received by the Kafka broker

### ISSUE THREAD

**Issue by jrask** [elastic/docs#358]
I spent some time digging into very strange behaviour before I realized that it was not the timestamp when it was received by the broker but rather the timestamp when the record was sent from the producing system.

By default, kafka uses CreateTime (in producer) but this can be overridden by setting `log.message.timestamp.type=LogAppendTime` in the broker config which is when the broker receives the message.

https://github.com/elastic/docs/blob/87e587a5f20b8a3752383f893166184a8336f8ef/html/en/logstash/6.x/plugins-inputs-kafka.html#L683

More info here https://kafka.apache.org/10/documentation.html#brokerconfigs

**Comment by dedemorton** [comment]
Unfortunately this issue was created in the wrong repository. The docs repository is for code and issues related to the tooling we use to build the docs.

Fortunately it looks like this problem is already resolved in the [latest docs](https://www.elastic.co/guide/en/logstash/current/plugins-inputs-kafka.html) so I am closing it now.
