### ISSUE TITLE
Add list of settings that are managed by centralized pipeline management

### ISSUE THREAD

**Issue by larry-hernandez** [elastic/docs#453]
It would be ideal to provide a list of setting that are managed by [centralized pipeline management](https://www.elastic.co/guide/en/logstash/6.4/logstash-centralized-pipeline-management.html#logstash-centralized-pipeline-management). This way customer know which settings they can exclude from logstash.yml. We should also note that pipeline settings included in the logstash.yml serve as defaults for settings included in logstash.yml.

At the moment we only note that pipeline.yml is ignored with an example of two settings.

![image](https://user-images.githubusercontent.com/36249578/48078413-038e8b80-e1af-11e8-8952-dacaa2fe6ba0.png)

**Comment by karenzone** [comment]
Note to self:  Look into this @karenzone

**Comment by dedemorton** [comment]
@karenzone I just noticed this request buried in the docs repo.

@larry-hernandez Unfortunately I think this issue got lost in this repo. This repo is for requests related to the tooling used to generate the docs. If this issue is still relevant, please open an issue in the correct product repo: https://github.com/elastic/logstash/issues/new
