### ISSUE TITLE
Kibana Canvas document link / availability issues

### ISSUE THREAD

**Issue by monfera** [elastic/docs#486]
1. https://www.elastic.co/guide/en/kibana/6.5/canvas.html seems to have no links to deeper content, eg. to the documentation of functions or tinymath
2. some documents eg. https://www.elastic.co/blog/kibana-canvas-metric-and-markdown-elements does link to https://canvas.elastic.co/reference/tinymath.html and https://canvas.elastic.co/reference/functions.html#filterrows (search for strings `math functions` and `filterrows`, respectively)
3. there can be difficulty answering community questions with no reference available, eg. [here](https://discuss.elastic.co/t/canvas-suitable-for-my-usecase/157651/3?u=monfera)

cc @rayafratkina

**Comment by gtback** [comment]
Hey @monfera, just checking if this was still an issue or if it's since been resolved. `canvas.elastic.co` seems to just be a redirect to https://www.elastic.co/guide/en/kibana/current/canvas.html. 

These pages all seem to exist now:
- https://www.elastic.co/guide/en/kibana/6.5/canvas-common-functions.html#_filterrows
- https://www.elastic.co/guide/en/kibana/6.5/canvas-tinymath-functions.html

I know 6.5 isn't supported anymore, but if there are issues in the current versions, it would probably be better to open them against the Kibana repo.

**Comment by monfera** [comment]
Thanks for checking @gtback - indeed these pages show up now, and probably have for a long while
