### ISSUE TITLE
dedicated master-eligible node explanation question

### ISSUE THREAD

**Issue by TomonoriSoejima** [elastic/docs#497]
https://www.elastic.co/guide/en/elasticsearch/reference/6.3/modules-node.html#modules-node-xpack

It says 

```
To create a dedicated master-eligible node when X-Pack is installed, set:
 
node.master: true 
node.data: false 
node.ingest: false 
node.ml: false 
xpack.ml.enabled: true 
```

But I believe you don't really need `xpack.ml.enabled: true `.
Was it a mistake that it is added there or it does really need to be set?

**Comment by lcawl** [comment]
I think there are two other pieces of important information in that page. 
1) "The xpack.ml.enabled setting is enabled by default" i.e. you are not required to explicitly set it.
2) "If you want to use X-Pack machine learning features in your cluster, you must enable machine learning (set xpack.ml.enabled to true) on all master-eligible nodes."

The latter is because that setting disables the machine learning APIs on the node. It cannot open jobs, start datafeeds, or receive transport (internal) communication requests related to machine learning APIs. 

I'll open a PR in the appropriate repo to see if I can make that clearer in the documentation.

**Comment by lcawl** [comment]
This issue was addressed in https://github.com/elastic/elasticsearch/pull/42812 and subsequent fixes to this content.
