### ISSUE TITLE
The hash of the docs build repo should count against the hash of all books

### ISSUE THREAD

**Issue by nik9000** [elastic/docs#593]
When you change the docs build repo that should force rebuilding all of the books at least in CI. Without this a change to the docs build repo might cause building a book to fail at a later date.

We might want to implement this in CI directly because we always have a hash there. We might even have a previous hash. OTOH it'd be more true to the project to store this in branches.yaml and check there. :shrug: I'll pick something.

**Comment by nik9000** [comment]
By a change to the docs repo I mean something like `attributes.asciidoc`.

**Comment by nik9000** [comment]
For what it is worth, I was wrong about elastic/elasticsearch#38674. I do still think this is a thing worth thinking about.

**Comment by lcawl** [comment]
In my opinion, ultimately we want to be able to specify which books should rebuild (per https://github.com/elastic/docs/issues/249) so that we wouldn't have to wait for all the books to build if we know specifically which ones are affected.

This enhancement might be a good failsafe, however, for cases where folks don't realize all the books that are impacted by their changes. It might slow things down a bit on release days when we're often checking in several changes to the docs repo, but as long as we can cancel some builds until we're done all the changes, it should be fine.

**Comment by dedemorton** [comment]
I think this is a good idea. At some point, the changes in the docs repo will settle down and be less common, so I wouldn't expect the full build to cause too many delays. Might be worth waiting until the dust settles on the current migration, tho

**Comment by debadair** [comment]
I think the benefits of automatically building when there's a change outweigh the downside of building everything more often. People tend to make changes that they don't realize have an effect beyond the book they were focused on and don't always realized when a full build is required. 

On a somewhat related note...the changes also mean that we could add version branches for the shared versions files now.
