### ISSUE TITLE
Drop usage of python 2

### ISSUE THREAD

**Issue by nik9000** [elastic/docs#636]
Python 2 has [about](https://pythonclock.org/) 10 months of maintenance left at the time of creating this issue. We should stop using it before it is no longer maintained..... I'm fairly sure we only use it in two places:

1. [x] AsciiDoc/a2x: These will go away when we switch to asciidoctor.
2. [ ] `build_docs` is python2 and python3 compatible because macOS doesn't come with python3 by default and we didn't want to ask anyone to `brew install python3`. Maybe we should though....

**Comment by ddillinger** [comment]
We also are trending toward dockerizing things. Instead of a host install, we could wrap it in docker. It'll be silly slow the first time someone has never had a python:3 image downloaded before, but a wash every time after that, and keeps us from touching their system whatsoever.

See also https://docs.docker.com/samples/library/python/#run-a-single-python-script

**Comment by nik9000** [comment]
Given that that the script's job is to rewrite arguments and launch docker, doing it with docker feels silly. Silly doesn't mean wrong though.....

**Comment by gtback** [comment]
I don't see a point to deliberately breaking Python 2 support in `build_docs`, since all the script does is wrap a Docker command. The point of that script (and its way of wrapping Docker) is to make it as easy as possible for anyone (with Python and Docker installed) to build the docs. I can see adding documentation that only Python 3 is "officially" supported (since Python 2 is EOL). I'm also open to other ways to make it easier to build the docs, but at that point I'd want to think about whether Python is the right choice at all.

**Comment by nik9000** [comment]
I'm quite ok keeping python2 support in `build_docs`. Everything shouldn't have it. But I think that is already done now that `a2x` is gone.

**Comment by gtback** [comment]
Closing this since there's nothing immediately actionable.
