### ISSUE TITLE
Feature / Process: redirect management

### ISSUE THREAD

**Issue by AnneB-SEO** [elastic/docs#656]
Per our meeting today (2/27/2019) with: @debadair @nik9000 @nrichers @sylvie777 @liztauscher

We'd like a feature and/or process that will enable the Docs Team to manage 301 doc redirects. This would include being able to identify current redirects and add new redirects.

Web Team's [redirect spreadsheet](https://docs.google.com/spreadsheets/d/1JjeZH0uF6_T5iSWXEIyEYXKMg8QC1p9htZQVCDcoX1M/edit?usp=sharing)

cc: @brianjolly

**Comment by nik9000** [comment]
I'm coming at this in a few stages:
* [ ] Commit the redirects that we have to the docs repo as "legacy" and build a redirects config out of them in the built-docs repo (#674). This is a nice start because one of our problems is that the list of redirects isn't accessible to everyone or editable by the docs team. This fixes that. It also makes the redirects available for testing locally with `./build_docs --all`.
* [ ] Switch the HTML redirects that we make to nginx redirects. These just bother me.
* [ ] Implement a way for an asciidoc file to declare "redirect this url to me" and start using it to generate the list of redirects. This seems like a fairly nice way to prevent things like redirects to 404s or just mistyped redirects. This'd only with Asciidoctor but we plan to shift everything to Asciidoctor before too long anyway.
* [ ] Slowly remove redirects from the legacy file by shifting redirects to being declared in the way I built above.

**Comment by debadair** [comment]
Relates to: #1820

**Comment by debadair** [comment]
Closing in favor of the more recent discussion.
