### ISSUE TITLE
Document that binary packages are not available for 32bit based Linux OSes

### ISSUE THREAD

**Issue by edmorley** [elastic/docs#85]
After following the steps here:
https://www.elastic.co/guide/en/elasticsearch/reference/current/setup-repositories.html

I received the following when trying to `sudo apt-get install elasticsearch`:

```
E: Unable to locate package elasticsearch.
```

Googling this returns several unhelpful suggestions from a few years ago in the top 3 results, whereas the actual cause of the problem can be found in:
https://discuss.elastic.co/t/cannot-install-2-1-from-debian-repository/35843
https://discuss.elastic.co/t/ubuntu-repo-not-working-solved/43043/15

...namely that there are only 64bit packages available, so I needed to switch the base 32bit Ubuntu trusty image I was using with Vagrant to the 64bit one.

Ideally this would be documented somewhere more clearly to save others hitting the same problem.

Perhaps on:
https://www.elastic.co/guide/en/elasticsearch/reference/current/setup-repositories.html

...and maybe even by adding a 64bit vs 32bit column here:
https://www.elastic.co/support/matrix#show_os

**Comment by dedemorton** [comment]
Closing because this issue is quite old and should have been opened in the https://github.com/elastic/elasticsearch repo.

**Comment by edmorley** [comment]
@dedemorton this issue was about the docs, so this seems like the right repository?
Just closing the issue because it's old is a little frustrating.

**Comment by dedemorton** [comment]
@edmorley Sorry for the confusion. The docs repository is for issues related to the doc build process and infrastructure. Errors in the documentation need to be reported in the repository that contains the source for the documentation (in this case, the repository is https://github.com/elastic/elasticsearch ). I apologize that someone didn't notify you of this earlier. I just happened to notice your issue because I was triaging old issues. I closed the issue because it was old *and* in the wrong repository. If it's still valid, please open the issue in the elasticsearch repo. Thanks for your comments.
