### ISSUE TITLE
Embedded videos

### ISSUE THREAD

**Issue by KOTungseth** [elastic/docs#995]
With all of the new videos that Kibana is making, we should add the ability to embed the videos right in our docs.

**Comment by debadair** [comment]
AsciiDoctor [supports this](https://asciidoctor.org/docs/asciidoc-syntax-quick-reference/#videos). I thought we had at least one place where we *did* embed a video, but maybe that doesn't actually render correctly given the current state of things.

**Comment by alaudazzi** [comment]
Relates to #32109.

**Comment by nik9000** [comment]
Another interesting thing about video: where do the videos go before and after the build? I imagine the source repos don't want big videos in them because it'll make their git operations much slower. The `build-docs` repo can probably hold them without an issue, but it *shouldn't* hold any videos that should be distributed to air gapped folks.

**Comment by alaudazzi** [comment]
Just for the sake of consistency, can we move and keep the conversation around videos in [#32109](https://github.com/elastic/cloud/issues/32109)? This is where the most recent exchanges and tests are collected.

**Comment by KOTungseth** [comment]
I'm going to close this issue. If embedded videos are supported in AsciiDoctor, then we can move forward with our video work in Kibana.
